### ISSUE TITLE
Está sendo aplicado juros composto no parcelamento porém deveria ser aplicado juros simples

### ISSUE THREAD

**Issue by laerte-guimaraes** [mentores-digital/vindi-plugin#56]
### Motivação
A opção de **taxa de juros ao mês** está aplicando juros compostos. Porém, deveriam aplicar juros simples
![image](https://user-images.githubusercontent.com/31661772/83929235-083f6b00-a769-11ea-9211-e9efe868cc84.png)

- No cenário atual o valor total e o valor das parcelas estão aumentando :thinking: 

#### Aplicando uma taxa de **50%** para um valor de **R$ 20,00**:
  ![image](https://user-images.githubusercontent.com/31661772/83924789-d1af2380-a75b-11ea-8447-6196e10dce54.png)
 
### 

Os valores deveriam ser:

| N° parcelas  | Valor parcelas | Valor total |
|---|---|---|
| 1x  | R$ 20.00 | R$ 20.00 | 
|  2x | R$ 15,00 | R$ 30.00 | 
|  3x | R$ 13,33 | R$ 40.00 | 
|  4x | R$ 12,50 | R$ 50.00 | 

Sendo assim, o valor total aumenta, e o valor das parcelas abaixa :wink:

**Comment by thihxm** [comment]
Bom dia @laerte-guimaraes , você está utilizando a versão mais recente do branch develop? Essa questão do valor não estar sendo atualizado já está funcionando na versão mais recente. Tirando isso, já estou fazendo a troca para juros simples.
